spring:
  application:
    name: hystrix-demo

server:
  port: 9900
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: BASIC
        connectTimeout: 2000
        readTimeout: 2000